// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "index.proto" (package "safety_web", syntax proto3)
// tslint:disable
//
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Safety-web summary-related messages

/**
 * Summary is tied to a package, not a repo.
 *
 * @generated from protobuf message safety_web.PackageSummary
 */
export interface PackageSummary {
    /**
     * @generated from protobuf field: string summaryVersion = 1;
     */
    summaryVersion: string; // Version of the summary format definition
    /**
     * @generated from protobuf field: string packageName = 2;
     */
    packageName: string;
    /**
     * @generated from protobuf field: string packageVersion = 3;
     */
    packageVersion: string;
    /**
     * @generated from protobuf field: string packagePath = 4;
     */
    packagePath: string; // Relative path of the package in the repository
    /**
     * @generated from protobuf field: safety_web.Repository repository = 5;
     */
    repository?: Repository; // Metadata about the repository scanned
    /**
     * @generated from protobuf field: repeated safety_web.Violation violations = 6;
     */
    violations: Violation[];
}
/**
 * @generated from protobuf message safety_web.Repository
 */
export interface Repository {
    /**
     * @generated from protobuf field: string url = 1;
     */
    url: string;
    /**
     * @generated from protobuf field: optional string commitId = 2;
     */
    commitId?: string;
}
/**
 * These messages are not stable and may still be changed in a breaking way
 * while we figure out what's useful.
 *
 * @generated from protobuf message safety_web.Violation
 */
export interface Violation {
    /**
     * @generated from protobuf field: string category = 1;
     */
    category: string; // Free form string, but is more of an enum. e.g. all TT violations should be "trusted-types"
    /**
     * @generated from protobuf field: string rule_id = 2;
     */
    ruleId: string; // e.g. "ban-element-innerhtml-assignments"
    /**
     * @generated from protobuf field: safety_web.ConfidenceLevel confidence = 3;
     */
    confidence: ConfidenceLevel;
    /**
     * @generated from protobuf field: safety_web.Location location = 5;
     */
    location?: Location;
    /**
     * @generated from protobuf field: optional safety_web.Exemption exemption = 6;
     */
    exemption?: Exemption;
}
/**
 * @generated from protobuf message safety_web.Location
 */
export interface Location {
    /**
     * @generated from protobuf field: string filepath = 1;
     */
    filepath: string;
    /**
     * @generated from protobuf field: int32 line = 2;
     */
    line: number;
    /**
     * @generated from protobuf field: int32 column = 3;
     */
    column: number;
    /**
     * @generated from protobuf field: int32 end_line = 4;
     */
    endLine: number;
    /**
     * @generated from protobuf field: int32 end_column = 5;
     */
    endColumn: number;
}
/**
 * @generated from protobuf message safety_web.Exemption
 */
export interface Exemption {
    /**
     * @generated from protobuf field: safety_web.ExemptionType type = 1;
     */
    type: ExemptionType;
    /**
     * @generated from protobuf field: string justification = 2;
     */
    justification: string;
}
/**
 * @generated from protobuf enum safety_web.ConfidenceLevel
 */
export enum ConfidenceLevel {
    /**
     * @generated from protobuf enum value: VIOLATION = 0;
     */
    VIOLATION = 0,
    /**
     * @generated from protobuf enum value: MEDIUM_POTENTIAL_VIOLATION = 1;
     */
    MEDIUM_POTENTIAL_VIOLATION = 1,
    /**
     * @generated from protobuf enum value: LOW_POTENTIAL_VIOLATION = 2;
     */
    LOW_POTENTIAL_VIOLATION = 2
}
/**
 * @generated from protobuf enum safety_web.ExemptionType
 */
export enum ExemptionType {
    /**
     * @generated from protobuf enum value: UNKNOWN_TYPE = 0;
     */
    UNKNOWN_TYPE = 0,
    /**
     * Violation is tracked in a safety-web allowlist
     *
     * @generated from protobuf enum value: ALLOWLISTED = 1;
     */
    ALLOWLISTED = 1,
    /**
     * Violation is silenced using ESLint comments
     *
     * @generated from protobuf enum value: ESLINT_SILENCED = 2;
     */
    ESLINT_SILENCED = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class PackageSummary$Type extends MessageType<PackageSummary> {
    constructor() {
        super("safety_web.PackageSummary", [
            { no: 1, name: "summaryVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "packageName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "packageVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "packagePath", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "repository", kind: "message", T: () => Repository },
            { no: 6, name: "violations", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Violation }
        ]);
    }
    create(value?: PartialMessage<PackageSummary>): PackageSummary {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.summaryVersion = "";
        message.packageName = "";
        message.packageVersion = "";
        message.packagePath = "";
        message.violations = [];
        if (value !== undefined)
            reflectionMergePartial<PackageSummary>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PackageSummary): PackageSummary {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string summaryVersion */ 1:
                    message.summaryVersion = reader.string();
                    break;
                case /* string packageName */ 2:
                    message.packageName = reader.string();
                    break;
                case /* string packageVersion */ 3:
                    message.packageVersion = reader.string();
                    break;
                case /* string packagePath */ 4:
                    message.packagePath = reader.string();
                    break;
                case /* safety_web.Repository repository */ 5:
                    message.repository = Repository.internalBinaryRead(reader, reader.uint32(), options, message.repository);
                    break;
                case /* repeated safety_web.Violation violations */ 6:
                    message.violations.push(Violation.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PackageSummary, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string summaryVersion = 1; */
        if (message.summaryVersion !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.summaryVersion);
        /* string packageName = 2; */
        if (message.packageName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.packageName);
        /* string packageVersion = 3; */
        if (message.packageVersion !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.packageVersion);
        /* string packagePath = 4; */
        if (message.packagePath !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.packagePath);
        /* safety_web.Repository repository = 5; */
        if (message.repository)
            Repository.internalBinaryWrite(message.repository, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* repeated safety_web.Violation violations = 6; */
        for (let i = 0; i < message.violations.length; i++)
            Violation.internalBinaryWrite(message.violations[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.PackageSummary
 */
export const PackageSummary = new PackageSummary$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Repository$Type extends MessageType<Repository> {
    constructor() {
        super("safety_web.Repository", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "commitId", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Repository>): Repository {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<Repository>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Repository): Repository {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* optional string commitId */ 2:
                    message.commitId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Repository, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* optional string commitId = 2; */
        if (message.commitId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.commitId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.Repository
 */
export const Repository = new Repository$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Violation$Type extends MessageType<Violation> {
    constructor() {
        super("safety_web.Violation", [
            { no: 1, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "rule_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "confidence", kind: "enum", T: () => ["safety_web.ConfidenceLevel", ConfidenceLevel] },
            { no: 5, name: "location", kind: "message", T: () => Location },
            { no: 6, name: "exemption", kind: "message", T: () => Exemption }
        ]);
    }
    create(value?: PartialMessage<Violation>): Violation {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.category = "";
        message.ruleId = "";
        message.confidence = 0;
        if (value !== undefined)
            reflectionMergePartial<Violation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Violation): Violation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string category */ 1:
                    message.category = reader.string();
                    break;
                case /* string rule_id */ 2:
                    message.ruleId = reader.string();
                    break;
                case /* safety_web.ConfidenceLevel confidence */ 3:
                    message.confidence = reader.int32();
                    break;
                case /* safety_web.Location location */ 5:
                    message.location = Location.internalBinaryRead(reader, reader.uint32(), options, message.location);
                    break;
                case /* optional safety_web.Exemption exemption */ 6:
                    message.exemption = Exemption.internalBinaryRead(reader, reader.uint32(), options, message.exemption);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Violation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string category = 1; */
        if (message.category !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.category);
        /* string rule_id = 2; */
        if (message.ruleId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.ruleId);
        /* safety_web.ConfidenceLevel confidence = 3; */
        if (message.confidence !== 0)
            writer.tag(3, WireType.Varint).int32(message.confidence);
        /* safety_web.Location location = 5; */
        if (message.location)
            Location.internalBinaryWrite(message.location, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional safety_web.Exemption exemption = 6; */
        if (message.exemption)
            Exemption.internalBinaryWrite(message.exemption, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.Violation
 */
export const Violation = new Violation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Location$Type extends MessageType<Location> {
    constructor() {
        super("safety_web.Location", [
            { no: 1, name: "filepath", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "line", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "column", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "end_line", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "end_column", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Location>): Location {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.filepath = "";
        message.line = 0;
        message.column = 0;
        message.endLine = 0;
        message.endColumn = 0;
        if (value !== undefined)
            reflectionMergePartial<Location>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Location): Location {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string filepath */ 1:
                    message.filepath = reader.string();
                    break;
                case /* int32 line */ 2:
                    message.line = reader.int32();
                    break;
                case /* int32 column */ 3:
                    message.column = reader.int32();
                    break;
                case /* int32 end_line */ 4:
                    message.endLine = reader.int32();
                    break;
                case /* int32 end_column */ 5:
                    message.endColumn = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Location, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string filepath = 1; */
        if (message.filepath !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.filepath);
        /* int32 line = 2; */
        if (message.line !== 0)
            writer.tag(2, WireType.Varint).int32(message.line);
        /* int32 column = 3; */
        if (message.column !== 0)
            writer.tag(3, WireType.Varint).int32(message.column);
        /* int32 end_line = 4; */
        if (message.endLine !== 0)
            writer.tag(4, WireType.Varint).int32(message.endLine);
        /* int32 end_column = 5; */
        if (message.endColumn !== 0)
            writer.tag(5, WireType.Varint).int32(message.endColumn);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.Location
 */
export const Location = new Location$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Exemption$Type extends MessageType<Exemption> {
    constructor() {
        super("safety_web.Exemption", [
            { no: 1, name: "type", kind: "enum", T: () => ["safety_web.ExemptionType", ExemptionType] },
            { no: 2, name: "justification", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Exemption>): Exemption {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.justification = "";
        if (value !== undefined)
            reflectionMergePartial<Exemption>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Exemption): Exemption {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* safety_web.ExemptionType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* string justification */ 2:
                    message.justification = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Exemption, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* safety_web.ExemptionType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* string justification = 2; */
        if (message.justification !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.justification);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.Exemption
 */
export const Exemption = new Exemption$Type();
