// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "pipeline.proto" (package "safety_web.pipeline", syntax proto3)
// tslint:disable
//
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PackageSummary } from "./index";
/**
 * Captures the project setup used during the analysis
 *
 * @generated from protobuf message safety_web.pipeline.RepoConfig
 */
export interface RepoConfig {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string url = 2;
     */
    url: string;
    /**
     * @generated from protobuf field: string commit = 3;
     */
    commit: string;
}
/**
 * @generated from protobuf message safety_web.pipeline.Package
 */
export interface Package {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string relative_path = 2;
     */
    relativePath: string;
    /**
     * @generated from protobuf field: string version = 3;
     */
    version: string;
    /**
     * @generated from protobuf field: safety_web.PackageSummary safety_web_summary = 4;
     */
    safetyWebSummary?: PackageSummary;
    /**
     * @generated from protobuf field: string outcome = 5;
     */
    outcome: string;
}
/**
 * @generated from protobuf message safety_web.pipeline.PackageManager
 */
export interface PackageManager {
    /**
     * @generated from protobuf field: string kind = 1;
     */
    kind: string;
    /**
     * @generated from protobuf field: string version = 2;
     */
    version: string;
}
/**
 * An invocation of the pipeline on 1 repository. Captures characteristics found
 * while analyzing and installing the repository.
 *
 * @generated from protobuf message safety_web.pipeline.Repository
 */
export interface Repository {
    /**
     * @generated from protobuf field: string url = 1;
     */
    url: string;
    /**
     * @generated from protobuf field: safety_web.pipeline.PackageManager package_manager_found = 3;
     */
    packageManagerFound?: PackageManager;
    /**
     * @generated from protobuf field: safety_web.pipeline.PackageManager package_manager_used = 4;
     */
    packageManagerUsed?: PackageManager;
    /**
     * @generated from protobuf field: repeated safety_web.pipeline.Package packages = 5;
     */
    packages: Package[];
    /**
     * @generated from protobuf field: string logs = 6;
     */
    logs: string;
    /**
     * When the repository fails to be set up, record the failing step.
     *
     * @generated from protobuf field: string step_failure = 7;
     */
    stepFailure: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class RepoConfig$Type extends MessageType<RepoConfig> {
    constructor() {
        super("safety_web.pipeline.RepoConfig", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "commit", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RepoConfig>): RepoConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.url = "";
        message.commit = "";
        if (value !== undefined)
            reflectionMergePartial<RepoConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RepoConfig): RepoConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string url */ 2:
                    message.url = reader.string();
                    break;
                case /* string commit */ 3:
                    message.commit = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RepoConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string url = 2; */
        if (message.url !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.url);
        /* string commit = 3; */
        if (message.commit !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.commit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.pipeline.RepoConfig
 */
export const RepoConfig = new RepoConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Package$Type extends MessageType<Package> {
    constructor() {
        super("safety_web.pipeline.Package", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "relative_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "safety_web_summary", kind: "message", T: () => PackageSummary },
            { no: 5, name: "outcome", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Package>): Package {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.relativePath = "";
        message.version = "";
        message.outcome = "";
        if (value !== undefined)
            reflectionMergePartial<Package>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Package): Package {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string relative_path */ 2:
                    message.relativePath = reader.string();
                    break;
                case /* string version */ 3:
                    message.version = reader.string();
                    break;
                case /* safety_web.PackageSummary safety_web_summary */ 4:
                    message.safetyWebSummary = PackageSummary.internalBinaryRead(reader, reader.uint32(), options, message.safetyWebSummary);
                    break;
                case /* string outcome */ 5:
                    message.outcome = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Package, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string relative_path = 2; */
        if (message.relativePath !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.relativePath);
        /* string version = 3; */
        if (message.version !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.version);
        /* safety_web.PackageSummary safety_web_summary = 4; */
        if (message.safetyWebSummary)
            PackageSummary.internalBinaryWrite(message.safetyWebSummary, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string outcome = 5; */
        if (message.outcome !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.outcome);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.pipeline.Package
 */
export const Package = new Package$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PackageManager$Type extends MessageType<PackageManager> {
    constructor() {
        super("safety_web.pipeline.PackageManager", [
            { no: 1, name: "kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PackageManager>): PackageManager {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = "";
        message.version = "";
        if (value !== undefined)
            reflectionMergePartial<PackageManager>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PackageManager): PackageManager {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string kind */ 1:
                    message.kind = reader.string();
                    break;
                case /* string version */ 2:
                    message.version = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PackageManager, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string kind = 1; */
        if (message.kind !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.kind);
        /* string version = 2; */
        if (message.version !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.version);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.pipeline.PackageManager
 */
export const PackageManager = new PackageManager$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Repository$Type extends MessageType<Repository> {
    constructor() {
        super("safety_web.pipeline.Repository", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "package_manager_found", kind: "message", T: () => PackageManager },
            { no: 4, name: "package_manager_used", kind: "message", T: () => PackageManager },
            { no: 5, name: "packages", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Package },
            { no: 6, name: "logs", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "step_failure", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Repository>): Repository {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        message.packages = [];
        message.logs = "";
        message.stepFailure = "";
        if (value !== undefined)
            reflectionMergePartial<Repository>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Repository): Repository {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* safety_web.pipeline.PackageManager package_manager_found */ 3:
                    message.packageManagerFound = PackageManager.internalBinaryRead(reader, reader.uint32(), options, message.packageManagerFound);
                    break;
                case /* safety_web.pipeline.PackageManager package_manager_used */ 4:
                    message.packageManagerUsed = PackageManager.internalBinaryRead(reader, reader.uint32(), options, message.packageManagerUsed);
                    break;
                case /* repeated safety_web.pipeline.Package packages */ 5:
                    message.packages.push(Package.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string logs */ 6:
                    message.logs = reader.string();
                    break;
                case /* string step_failure */ 7:
                    message.stepFailure = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Repository, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* safety_web.pipeline.PackageManager package_manager_found = 3; */
        if (message.packageManagerFound)
            PackageManager.internalBinaryWrite(message.packageManagerFound, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* safety_web.pipeline.PackageManager package_manager_used = 4; */
        if (message.packageManagerUsed)
            PackageManager.internalBinaryWrite(message.packageManagerUsed, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated safety_web.pipeline.Package packages = 5; */
        for (let i = 0; i < message.packages.length; i++)
            Package.internalBinaryWrite(message.packages[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* string logs = 6; */
        if (message.logs !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.logs);
        /* string step_failure = 7; */
        if (message.stepFailure !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.stepFailure);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message safety_web.pipeline.Repository
 */
export const Repository = new Repository$Type();
